use std::collections::{HashSet, VecDeque};
use std::error::Error;

use futures::{stream, StreamExt};

use crate::anime_service::AnimeService;
use crate::model::{Anime, Edge, RelatedAnime, RelationType};
use crate::model_dto::ContentGraphDTO;

// Bump this whenever the graph construction algorithm changes. This prevents
// graphs generated by an older algorithm from being served from the cache.
const GRAPH_CACHE_TYPE: &str = "anime_graph_v2";
const GRAPH_CACHE_TTL_SECS: i64 = 60 * 60 * 24;

/// Build a related-anime graph without recursively re-fetching the root.
///
/// The complete graph is cached separately from anime-detail data. This is
/// important because anime-detail caches can legitimately live for a long
/// time, while a graph cache must be invalidated whenever the graph algorithm
/// changes.
pub async fn get_related_anime(
    service: &AnimeService,
    id: i64,
) -> Result<ContentGraphDTO, Box<dyn Error>> {
    if let Some(cached_graph) = service
        .cache_service
        .get_cache_by_id::<ContentGraphDTO>(GRAPH_CACHE_TYPE, id.to_string())
        .await
    {
        println!("Graph cache hit for anime {}", id);
        return Ok(cached_graph);
    }

    println!("Graph cache miss for anime {}", id);

    // Always prefer the anime-detail cache first. The old implementation
    // deliberately bypassed it for the root and then fetched the root a
    // second time from the queue, which made repeated graph tests expensive.
    let root = get_anime_by_id(service, id).await?;

    let mut graph = ContentGraphDTO {
        nodes: HashSet::new(),
        edges: Vec::new(),
    };
    graph.nodes.insert(root.clone().into());

    let mut visited = HashSet::new();
    visited.insert(id);

    let root_edges = get_edges(id, root.related_anime.clone(), true);
    for edge in root_edges {
        if visited.insert(edge.target) {
            graph.edges.push(edge.clone().into());
        }
    }

    let mut queue: VecDeque<i64> = graph
        .edges
        .iter()
        .map(|edge| edge.target)
        .collect();

    while !queue.is_empty() {
        // Keep the MAL request burst deliberately small. MAL's public API does
        // not publish a precise limit, and conservative request pacing avoids
        // turning a large graph into a sequence of 429 retries.
        let mut batch = Vec::with_capacity(2);
        while batch.len() < 2 {
            let Some(current_id) = queue.pop_front() else { break };
            batch.push(current_id);
        }

        // Preserve input order so graph construction remains deterministic.
        // This also keeps the layout stable between requests.
        let results = stream::iter(batch)
            .map(|current_id| async move {
                match get_anime_by_id(service, current_id).await {
                    Ok(anime) => Some((current_id, anime)),
                    Err(error) => {
                        println!(
                            "Graph node fetch failed for anime {}: {}",
                            current_id, error
                        );
                        None
                    }
                }
            })
            .buffered(2)
            .collect::<Vec<_>>()
            .await;

        for result in results.into_iter().flatten() {
            let (current_id, anime) = result;
            graph.nodes.insert(anime.clone().into());

            // Only add an edge when its target is a new node. This keeps the
            // graph traversal acyclic and avoids the dense cross-links that
            // made large franchise graphs difficult to lay out.
            for edge in get_edges(current_id, anime.related_anime.clone(), false) {
                if visited.insert(edge.target) {
                    graph.edges.push(edge.clone().into());
                    queue.push_back(edge.target);
                }
            }
        }
    }

    // Store the fully generated graph. Subsequent opens of the same anime are
    // then a single cache lookup instead of dozens of MAL requests.
    service
        .cache_service
        .set_cache_by_id(
            GRAPH_CACHE_TYPE,
            id.to_string(),
            &graph,
            Some(GRAPH_CACHE_TTL_SECS),
        )
        .await;

    println!(
        "Graph cached for anime {}: {} nodes, {} edges",
        id,
        graph.nodes.len(),
        graph.edges.len()
    );

    Ok(graph)
}

async fn get_anime_by_id(service: &AnimeService, id: i64) -> Result<Anime, Box<dyn Error>> {
    if let Some(anime) = service
        .cache_service
        .get_cache_by_id::<Anime>("anime", id.to_string())
        .await
    {
        return Ok(anime);
    }

    let anime = service.mal_api.get_anime_details(id).await?;
    service
        .cache_service
        .set_cache_by_id("anime", id.to_string(), &anime, None)
        .await;
    Ok(anime)
}

fn get_edges(
    id: i64,
    related_anime: Option<Vec<RelatedAnime>>,
    include_others: bool,
) -> Vec<Edge> {
    related_anime
        .unwrap_or_default()
        .into_iter()
        .filter(|related| valid_relation(&related.relation_type, include_others))
        .map(|related| Edge {
            source: id,
            target: related.node.id,
            relation_type: related.relation_type,
        })
        .collect()
}

fn valid_relation(relation_type: &RelationType, include_others: bool) -> bool {
    match relation_type {
        RelationType::AlternativeSetting
        | RelationType::Sequel
        | RelationType::Prequel
        | RelationType::AlternativeVersion
        | RelationType::SideStory
        | RelationType::ParentStory
        | RelationType::Summary
        | RelationType::FullStory
        | RelationType::SpinOff => true,
        RelationType::Character => false,
        RelationType::Other => include_others,
    }
}
